device: "cuda"
seed: 77
env:
    env_name: "HumanoidBulletEnv-v0"
    num_envs: 30
    state_dim: 44
    action_dim: 17
checkpoint_path: "checkpoints/Humanoid"
actor:
    action_std_init: 0.4
    action_std_decay_rate: 0.01
    min_action_std: 0.1
    action_std_decay_freq: 3e5
    optimizer:
        lr: 2e-6
        momentum: 0.9
        weight_decay: 5e-4
critic:
    optimizer:
        lr: 5e-4
        momentum: 0.9
        weight_decay: 0
train: 
    total_timesteps: 20000000
    max_episode_len: 1024
    gamma: 0.99
    tau: 0.95
    coef_task_specific: 0.5
    coef_task_agnostic: 0.6
    ppo:
        loss_type: clip
        epochs: 10
        batch_size: 960    
        eps_clip: 0.2
        coef_value_function: 0.5
        coef_entropy_penalty: 0
        value_clipping: True
    gail:
        use: True
        data_dir: "data/locomotion/run"
        asf_dir: "data/asf"
        hidden_dim: 256
        optimizer:
            lr: 1e-5 
            weight_decay: 0.2
        epochs: 10
        batch_size: 512
        gradient_penalty_weight: 10
    reward_scaler: True
    observation_normalizer: True
    clipping_gradient: True
    scheduler: True
    average_interval: 100
    max_ckpt_count: 3