device: "cpu"
seed: 77
env:
    env_name: null
    num_envs: 10
    state_dim: 225
    action_dim: 28
checkpoint_path: "checkpoints/Humanoid"
actor:
    action_std_init: 0.4
    action_std_decay_rate: 0.01
    min_action_std: 0.1
    action_std_decay_freq: 3e5
    hidden_dim: [1024, 512]
    init_scaling: 0.01
    optimizer:
        lr: 2e-5
        weight_decay: 5e-4
critic:
    hidden_dim: [1024, 512]
    init_scaling: 1
    optimizer:
        lr: 5e-4
        weight_decay: 0
train: 
    total_timesteps: 20000000
    max_episode_len: 100
    gamma: 0.95
    tau: 0.95
    task_reward_lerp: 0.5
    style_reward_scale: 2.0
    ppo:
        loss_type: clip
        epochs: 5
        batch_size: 480    
        eps_clip: 0.2
        coef_value_function: 0.5
        coef_entropy_penalty: 0
        value_clipping: True
    gail:
        use: True
        motion_files: ["data/deepmimic/humanoid3d_run.txt", "data/deepmimic/humanoid3d_walk.txt"]
        skeleton_file: "data/deepmimic/humanoid3d.txt"
        hidden_dim: [1024, 512]
        init_scaling: 1
        optimizer:
            lr: 1e-5 
            weight_decay: 0.2
        epochs: 10
        batch_size: 512
        gradient_penalty_weight: 10
    reward_scaler: True
    observation_normalizer: True
    clipping_gradient: True
    scheduler: True
    average_interval: 100
    max_ckpt_count: 3