device: "cuda"
seed: 77
env:
    env_name: "AMP_Env/Builds/TargetHeading/TargetHeading"
    num_envs: 10
    state_dim: 225
    goal_dim: 3
    action_dim: 28
checkpoint_path: "checkpoints/Humanoid"
actor:
    action_std_init: 0.2
    action_std_decay_freq: 3e5
    hidden_dim: [1024, 512]
    init_scaling: 1
    optimizer:
        lr: 1e-4
        weight_decay: 5e-4
critic:
    hidden_dim: [1024, 512]
    init_scaling: 1
    optimizer:
        lr: 1e-4
        weight_decay: 0
train: 
    total_timesteps: 20000000
    max_episode_len: 1000
    buffer_size: 20480
    gamma: 0.99
    tau: 0.95
    ppo:
        loss_type: clip
        epochs: 5
        batch_size: 2048    
        eps_clip: 0.2
        coef_value_function: 0.5
        coef_entropy_penalty: 0.001
        value_clipping: True
    gail:
        use: False
        task_reward_lerp: 0.5
        style_reward_scale: 2.0
        dataset_file: "data/datasets/humanoid3d_clips_locomotion.txt" 
        skeleton_file: "data/characters/humanoid3d.txt"
        hidden_dim: [1024, 512]
        init_scaling: 1
        optimizer:
            lr: 1e-5 
            weight_decay: 0.2
        epochs: 2
        batch_size: 256
        gradient_penalty_weight: 10
    reward_scaler: True
    observation_normalizer: True
    goal_normalizer: True
    clipping_gradient: True
    scheduler: True
    average_interval: 100
    max_ckpt_count: 3